attentionRegionDetection:
	mcc -m attention_region_detection_script.m

clean:
	rm -rf attention_region_detection_script 
	rm -rf attention_region_detection_script_main.c 
	rm -rf attention_region_detection_script_mcc_component_data.c 
	rm -rf attention_region_detection_script.prj 
	rm -rf mccExcludedFiles.log 
	rm -rf readme.txt 
	rm -rf run_attention_region_detection_script.sh
